# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jal Panchal
email:
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog about my journey in the world of technology and science.
#baseurl: "/about" # the subpath of your site, e.g. /blog
url: "https://jalpanchal.github.io" # the base hostname & protocol for your site
repository: "jalpanchal/jalpanchal.github.io" # the base repository for your site
twitter_username: jalponcho
github_username: jalpanchal
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
# remote_theme: mmistakes/minimal-mistakes@4.27.1
theme: null
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
breadcrumbs:
  enabled: true
  separator: " / "
  home: "Home"
  archive: "Archive"
  categories: "Categories"
  tags: "Tags"


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jal Panchal"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "A R&D scientist democratizing healthcare"
  location: "Boston, MA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jalpanchal/"
    # - label: "X"
    #   icon: "fa-brands fa-square-x-twitter"
    #   url: "https://x.com/jalponcho"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/jalpanchal"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jalpanchal/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      enable_copy_code_button: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

head_scripts:
  - /assets/css/custom.css
